### ISSUE TITLE
Закрытие потока, опечатка ?

### ISSUE THREAD

**Issue by itopt** [innovait-rus/NativeAPI#2]
Здравствуйте!
В функции innNative::mClose() для #ifdef _WINDOWS
опечатка "open" вместо "close"
https://github.com/innovait-rus/NativeAPI/blob/f5a059b5cd3b1e3170a42cbbea4878aeec223104/innNative.cpp#L549

Спасибо Вам за пример ВК!

**Comment by innovait-rus** [comment]
Да. Похоже на то. Мне она для линукс нужна была. На днях поправлю

**Comment by itopt** [comment]
Буду пробовать к вашему шаблону прикрутить работу с купюро-приемником
[https://github.com/frostasm/ccnet-cashcode](url)
С предвкушением и с содроганием.
В с++ джуниор)

**Comment by innovait-rus** [comment]
Ну я тоже писал подсматривая. В спп тоже ноль. Так что помочь не смогу.
